"""seed_v2 — 50+ versioned knowledge terms (deterministic, not LLM)."""

from __future__ import annotations

from backend.knowledge.models import KnowledgeCategory as C
from backend.knowledge.models import KnowledgeEntry as E


def _e(
    term: str,
    short: str,
    category: C,
    *,
    full: str | None = None,
    formula: str | None = None,
    formula_id: str | None = None,
    variables: list[str] | None = None,
    examples: list[str] | None = None,
    mistakes: list[str] | None = None,
    related: list[str] | None = None,
    aliases: list[str] | None = None,
) -> E:
    return E(
        term=term,
        category=category,
        short_definition=short,
        full_definition=full or short,
        definition=short,
        formula=formula,
        formula_id=formula_id,
        variables=variables or [],
        examples=examples or [],
        common_mistakes=mistakes or [],
        related_terms=related or [],
        aliases=aliases or [],
        source="argus_knowledge_v2",
        version="2.0",
        valid_from="2026-01-01",
    )


def build_seed_entries_v2() -> list[E]:
    e: list[E] = []

    # ── ECONOMICS / UNIT ──────────────────────────────────────────────────
    e += [
        _e("revenue", "Выручка — деньги от продаж до вычета известных расходов.", C.ECONOMICS,
           full="На маркетплейсе обычно Price×Orders (или UnitsSold). Не путать с прибылью.",
           formula="Revenue = Price × Orders", formula_id="F_REVENUE",
           variables=["price", "orders"],
           examples=["Цена 1000 ₽ × 80 заказов = 80 000 ₽ выручки."],
           mistakes=["Путать выручку с прибылью."],
           related=["profit", "AOV", "orders"], aliases=["выручка"]),
        _e("profit", "Прибыль — выручка минус только известные затраты.", C.ECONOMICS,
           full="Неизвестные расходы не выдумываются (статус MISSING/NOT_INCLUDED).",
           formula="Profit = Revenue − KnownCosts", formula_id="F_PROFIT",
           variables=["revenue", "known_costs"],
           mistakes=["Считать «точную» прибыль без комиссии/логистики/рекламы."],
           related=["margin", "markup", "COGS"], aliases=["прибыль", "профит"]),
        _e("gross_profit", "Валовая прибыль — выручка минус себестоимость (COGS).", C.ECONOMICS,
           formula="GrossProfit = Revenue − COGS", formula_id="F_GROSS_PROFIT",
           variables=["revenue", "cogs"],
           related=["COGS", "operating_profit"], aliases=["валовая прибыль", "gross profit"]),
        _e("operating_profit", "Операционная прибыль — после известных операционных расходов (логистика, комиссия, реклама… если переданы).", C.ECONOMICS,
           mistakes=["Выдумывать операционные статьи."],
           related=["profit", "contribution_margin"], aliases=["операционная прибыль"]),
        _e("margin", "Маржа — доля прибыли в выручке. Это НЕ наценка.", C.UNIT_ECONOMICS,
           full="Margin% = Profit / Revenue × 100. Markup% = (Price−Cost)/Cost × 100.",
           formula="Margin% = Profit / Revenue × 100", formula_id="F_MARGIN",
           variables=["profit", "revenue"],
           examples=["Прибыль 200 при выручке 1000 → маржа 20%."],
           mistakes=["Маржа ≠ наценка.", "Считать маржу от себестоимости."],
           related=["markup", "profit"], aliases=["маржа", "маржинальность"]),
        _e("markup", "Наценка — прибыль относительно себестоимости (cost), не выручки.", C.UNIT_ECONOMICS,
           formula="Markup% = (SellingPrice − Cost) / Cost × 100", formula_id="F_MARKUP",
           variables=["selling_price", "cost"],
           mistakes=["Наценка ≠ маржа."],
           related=["margin", "COGS"], aliases=["наценка"]),
        _e("unit_economics", "Unit-экономика — экономика одной единицы/заказа: цена, известные затраты, прибыль, маржа, наценка, безубыточность.", C.UNIT_ECONOMICS,
           full="На WB: selling price − COGS − commission − logistics − storage − ads − returns − taxes − penalties (только KNOWN).",
           examples=["Сначала собери KNOWN costs, потом считай UnitProfit."],
           mistakes=["Выдавать точную маржу без известных затрат."],
           related=["margin", "UnitProfit", "COGS"],
           aliases=["unit economics", "юнит экономика", "юнит-экономика", "unit-экономика"]),
        _e("COGS", "Себестоимость проданных товаров (Cost of Goods Sold).", C.UNIT_ECONOMICS,
           formula="COGS = PurchasePrice × Units", formula_id="F_COGS",
           variables=["purchase_price", "units"],
           mistakes=["Включать рекламу в COGS."],
           related=["profit", "markup"], aliases=["себестоимость", "cogs"]),
        _e("себестоимость", "Себестоимость — затраты на товар до маркетплейс-наценок (обычно закупка + известная упаковка).", C.PROCUREMENT,
           related=["COGS", "закупка"], aliases=["cost"]),
        _e("contribution_margin", "Маржа вклада — выручка минус переменные известные затраты.", C.UNIT_ECONOMICS,
           formula="ContributionMargin = Revenue − VariableCosts", formula_id="F_CM",
           variables=["revenue", "variable_costs"],
           related=["break_even", "margin"], aliases=["contribution margin", "маржа вклада"]),
        _e("fixed_costs", "Постоянные затраты — не меняются с объёмом в коротком горизонте (если известны).", C.ECONOMICS,
           related=["variable_costs", "break_even"], aliases=["постоянные затраты", "fixed costs"]),
        _e("variable_costs", "Переменные затраты — растут с объёмом продаж (COGS, часть логистики и т.п.).", C.ECONOMICS,
           related=["fixed_costs", "contribution_margin"], aliases=["переменные затраты", "variable costs"]),
        _e("break_even", "Точка безубыточности — объём, при котором прибыль ≈ 0 при известных затратах.", C.UNIT_ECONOMICS,
           formula="BreakEvenUnits = FixedCosts / ContributionMarginPerUnit", formula_id="F_BE_UNITS",
           variables=["fixed_costs", "cm_per_unit"],
           mistakes=["Считать без известных затрат."],
           related=["contribution_margin"], aliases=["безубыточность", "точка безубыточности", "break-even"]),
        _e("cash_flow", "Денежный поток — движение денег (поступления − выплаты), не равна бухгалтерской прибыли.", C.FINANCE,
           related=["DDS", "profit"], aliases=["cash flow", "кэшфлоу"]),
        _e("ROI", "Return On Investment — прибыль к вложенному капиталу.", C.ECONOMICS,
           formula="ROI = Profit / Investment × 100", formula_id="F_ROI",
           variables=["profit", "investment"],
           related=["ROAS", "ROMI"], aliases=["roi"]),
        _e("ROAS", "Return On Ad Spend — выручка на рубль рекламы.", C.ECONOMICS,
           formula="ROAS = Revenue / AdSpend", formula_id="F_ROAS",
           variables=["revenue", "ad_spend"],
           mistakes=["Путать ROAS и ROMI."],
           related=["ROMI", "CPA"], aliases=["roas"]),
        _e("ROMI", "Return On Marketing Investment — возврат маркетинговых инвестиций.", C.ECONOMICS,
           formula="ROMI = (Revenue − MarketingCost) / MarketingCost × 100", formula_id="F_ROMI",
           variables=["revenue", "marketing_cost"],
           related=["ROAS"], aliases=["romi"]),
        _e("CAC", "Customer Acquisition Cost — стоимость привлечения клиента.", C.ECONOMICS,
           formula="CAC = AcquisitionCost / NewCustomers", formula_id="F_CAC",
           variables=["acquisition_cost", "new_customers"],
           related=["LTV", "CPA"], aliases=["cac"]),
        _e("CPL", "Cost Per Lead — цена лида.", C.MARKETING,
           formula="CPL = AdSpend / Leads", formula_id="F_CPL",
           variables=["ad_spend", "leads"],
           related=["lead", "CPA"], aliases=["cpl", "цена лида"]),
        _e("CPA", "Cost Per Action/Acquisition — цена целевого действия (часто заказа).", C.MARKETING,
           formula="CPA = AdSpend / Orders", formula_id="F_CPA",
           variables=["ad_spend", "orders"],
           related=["CAC", "CPO"], aliases=["cpa"]),
        _e("LTV", "Lifetime Value — доход с клиента за жизненный цикл. Без повторных покупок не вычисляется.", C.ECONOMICS,
           formula="LTV ≈ ARPU × Lifespan (только при известных входах)", formula_id="F_LTV",
           variables=["arpu", "lifespan"],
           mistakes=["Выдумывать LTV."],
           related=["ARPU", "CAC"], aliases=["ltv", "lifetime value"]),
        _e("ARPU", "Average Revenue Per User — средняя выручка на пользователя.", C.ECONOMICS,
           formula="ARPU = Revenue / Users", formula_id="F_ARPU",
           variables=["revenue", "users"],
           related=["AOV", "LTV"], aliases=["arpu"]),
        _e("AOV", "Average Order Value — средний чек.", C.ECONOMICS,
           formula="AOV = Revenue / Orders", formula_id="F_AOV",
           variables=["revenue", "orders"],
           related=["revenue", "ARPU"], aliases=["aov", "средний чек"]),
        _e("DDS", "ДДС — движение денежных средств (cash flow statement / отчёт).", C.FINANCE,
           related=["cash_flow"], aliases=["ддс", "движение денежных средств"]),
        _e("оборотный_капитал", "Оборотный капитал — средства, замороженные в товаре/дебиторке для оборота.", C.FINANCE,
           related=["оборачиваемость", "закупка"], aliases=["оборотный капитал", "working capital"]),
        _e("оборачиваемость", "Оборачиваемость — как быстро товар/капитал проходит цикл склад→продажа.", C.MARKETPLACE,
           related=["stock", "оборотный_капитал"], aliases=["оборочиваемость"]),
        _e("закупка", "Закупка — приобретение товара у поставщика (цена, объём, логистика до склада).", C.PROCUREMENT,
           related=["COGS", "поставка"], aliases=["procurement", "закупочная цена"]),
        _e("логистика", "Логистика — стоимость доставки/перемещения товара.", C.LOGISTICS,
           formula="Logistics = WeightKg × DeliveryPerKg (если обе известны)", formula_id="F_LOGISTICS",
           variables=["weight_kg", "delivery_per_kg"],
           related=["хранение", "commission"], aliases=["logistics", "доставка"]),
        _e("хранение", "Хранение — плата за нахождение товара на складе маркетплейса (если известна).", C.LOGISTICS,
           related=["логистика", "stock"], aliases=["storage", "storage fee"]),
        _e("возвраты", "Возвраты — доля/число возвращённых заказов; в прибыль входят только при известной сумме.", C.ECONOMICS,
           related=["orders", "profit"], aliases=["returns", "return rate"]),
        _e("комиссии", "Комиссия маркетплейса (вознаграждение) — %/сумма удержания с продажи.", C.FINANCE,
           mistakes=["Выдумывать % без кабинета/данных продавца."],
           related=["profit", "WB вознаграждение"], aliases=["комиссия", "commission"]),
        _e("налоги", "Налоги учитываются только если ставка/сумма известны — иначе NOT_INCLUDED.", C.FINANCE,
           mistakes=["Выдумывать налоговую ставку."],
           related=["profit"], aliases=["taxes", "tax"]),
        _e("рекламные_расходы", "Рекламный spend — известные затраты на продвижение.", C.MARKETING,
           related=["CPC", "ROAS", "CTR"], aliases=["реклама", "ad spend", "advertising"]),
        _e("UnitProfit", "Прибыль на единицу = цена продажи − известные затраты на единицу.", C.UNIT_ECONOMICS,
           formula="UnitProfit = SellingPrice − UnitCosts", formula_id="F_UNIT_PROFIT",
           variables=["selling_price", "unit_costs"],
           related=["MarginPerUnit", "margin"], aliases=["прибыль на единицу", "unit profit"]),
        _e("MarginPerUnit", "Маржа на единицу = UnitProfit / SellingPrice.", C.UNIT_ECONOMICS,
           formula="MarginPerUnit = UnitProfit / SellingPrice", formula_id="F_MARGIN_UNIT",
           variables=["unit_profit", "selling_price"],
           related=["UnitProfit", "margin"], aliases=["маржа на единицу"]),
    ]

    # ── MARKETING ─────────────────────────────────────────────────────────
    e += [
        _e("lead", "Лид — целевой интерес/контакт потенциального покупателя по вашей воронке.", C.MARKETING,
           full="lead ≠ click ≠ order ≠ customer. Клик — ещё не всегда лид.",
           examples=["Определи действие: заявка, корзина, подписка — и только тогда меряй CPL."],
           mistakes=["Считать каждый клик лидом."],
           related=["CPL", "funnel", "conversion"], aliases=["лид"]),
        _e("lead_generation", "Лидогенерация — привлечение лидов платным/органическим трафиком.", C.MARKETING,
           related=["lead", "traffic"], aliases=["лидогенерация", "lead generation"]),
        _e("funnel", "Воронка: показы → клики → заказы → продажи → выручка → прибыль.", C.MARKETING,
           related=["CTR", "CVR", "conversion"], aliases=["воронка", "conversion funnel", "sales funnel"]),
        _e("traffic", "Трафик — поток визитов/показов на карточку или витрину.", C.MARKETING,
           related=["organic_traffic", "paid_traffic"], aliases=["трафик"]),
        _e("impressions", "Показы — сколько раз объявление/карточка были показаны.", C.METRICS,
           related=["CTR", "clicks"], aliases=["показы"]),
        _e("clicks", "Клики — переходы в карточку/объявление.", C.METRICS,
           related=["CTR", "CVR"], aliases=["клики"]),
        _e("CTR", "Click-Through Rate — доля кликов от показов.", C.METRICS,
           full="Показывает привлекательность в выдаче. НЕ показывает качество страницы после клика (это CVR). Универсального «хороший CTR=5%» нет без контекста ниши.",
           formula="CTR = Clicks / Impressions × 100", formula_id="F_CTR",
           variables=["clicks", "impressions"],
           examples=["50 кликов / 1000 показов = 5% CTR."],
           mistakes=["Называть CTR низким без цифры.", "Путать CTR и CVR.", "Выдумывать бенчмарк 5%."],
           related=["CVR", "CPC", "funnel"], aliases=["ctr", "цтр", "кликабельность"]),
        _e("CVR", "Conversion Rate — доля заказов от кликов.", C.METRICS,
           full="Показывает, насколько карточка дожимает до заказа после клика.",
           formula="CVR = Orders / Clicks × 100", formula_id="F_CVR",
           variables=["orders", "clicks"],
           mistakes=["Путать CVR и CTR."],
           related=["CTR", "orders"], aliases=["cvr", "конверсия в заказ"]),
        _e("conversion", "Конверсия — переход между шагами воронки.", C.MARKETING,
           related=["CVR", "funnel"], aliases=["конверсия"]),
        _e("CPC", "Cost Per Click — цена клика.", C.MARKETING,
           formula="CPC = AdSpend / Clicks", formula_id="F_CPC",
           variables=["ad_spend", "clicks"],
           related=["CPM", "CTR"], aliases=["cpc", "цена клика"]),
        _e("CPM", "Cost Per Mille — цена за 1000 показов.", C.MARKETING,
           formula="CPM = AdSpend / Impressions × 1000", formula_id="F_CPM",
           variables=["ad_spend", "impressions"],
           related=["CPC"], aliases=["cpm"]),
        _e("retention", "Удержание — доля клиентов, возвращающихся/покупающих повторно.", C.MARKETING,
           related=["repeat_purchase", "LTV"], aliases=["удержание"]),
        _e("repeat_purchase", "Повторная покупка — заказ от уже купившего клиента.", C.MARKETING,
           related=["retention", "LTV"], aliases=["повторные покупки"]),
        _e("acquisition", "Acquisition — привлечение новых клиентов.", C.MARKETING,
           related=["CAC", "activation"], aliases=["привлечение"]),
        _e("activation", "Activation — первое ценное действие нового пользователя/покупателя.", C.MARKETING,
           related=["acquisition", "conversion"], aliases=["активация"]),
        _e("traffic_source", "Источник трафика — откуда пришёл визит (organic/paid/internal).", C.MARKETING,
           related=["organic_traffic", "paid_traffic"], aliases=["источник трафика"]),
        _e("organic_traffic", "Органический трафик — бесплатная выдача/поиск без прямой оплаты клика.", C.MARKETING,
           related=["paid_traffic", "SEO"], aliases=["органика", "organic traffic"]),
        _e("paid_traffic", "Платный трафик — рекламные кампании с spend.", C.MARKETING,
           related=["organic_traffic", "CPC"], aliases=["платный трафик", "paid traffic"]),
        _e("remarketing", "Ремаркетинг — повторный показ рекламы тем, кто уже взаимодействовал.", C.MARKETING,
           related=["paid_traffic"], aliases=["ретаргетинг", "retargeting"]),
        _e("creatives", "Креативы — визуалы/тексты рекламы и первого фото карточки.", C.MARKETING,
           related=["CTR", "offer"], aliases=["креативы"]),
        _e("offer_mkt", "Оффер (маркетинг) — ценностное предложение покупателю (не путать с офертой WB).", C.MARKETING,
           mistakes=["Путать marketing offer и юридическую оферту WB."],
           related=["positioning", "creatives"], aliases=["оффер", "offer"]),
        _e("positioning", "Позиционирование — чем товар отличается в голове покупателя.", C.MARKETING,
           related=["offer_mkt"], aliases=["позиционирование"]),
        _e("ab_test", "A/B тест — сравнение двух вариантов при прочих равных.", C.MARKETING,
           mistakes=["Менять сразу 5 вещей и называть это A/B."],
           related=["CTR", "CVR"], aliases=["a/b test", "аб тест", "a/b"]),
        _e("IP", "IP неоднозначен: Intellectual Property (права/бренд) или Internet Protocol. Без контекста не смешивать с CTR/CVR.", C.MARKETING,
           mistakes=["Путать IP-адрес, интеллектуальную собственность и метрики воронки."],
           aliases=["ip", "айпи"]),
    ]

    # ── MARKETPLACE ───────────────────────────────────────────────────────
    e += [
        _e("карточка_товара", "Карточка — страница SKU: фото, цена, описание, отзывы, характеристики.", C.MARKETPLACE,
           related=["SKU", "nmID", "reviews"], aliases=["карточка", "card", "карточка товара"]),
        _e("SKU", "Stock Keeping Unit — учётная единица ассортимента.", C.MARKETPLACE,
           related=["nmID", "stock"], aliases=["sku", "ску"]),
        _e("nmID", "nmID / article — идентификатор номенклатуры на Wildberries.", C.WILDBERRIES,
           related=["SKU", "карточка_товара"], aliases=["article", "артикул", "nm_id", "nmid"]),
        _e("категория", "Категория — классификация товара на площадке (влияет на комиссию/видимость).", C.MARKETPLACE,
           related=["комиссии"], aliases=["category", "предмет"]),
        _e("цена", "Цена продавца на витрине (может отличаться от «публичной» с СПП).", C.MARKETPLACE,
           mistakes=["Путать public_price и seller_price."],
           related=["публичная_цена", "скидка"], aliases=["price", "цена продажи"]),
        _e("публичная_цена", "Публичная цена — то, что видит покупатель (с учётом механик площадки).", C.MARKETPLACE,
           related=["цена"], aliases=["public price", "public_price"]),
        _e("скидка", "Скидка — снижение цены продавцом и/или механиками WB.", C.MARKETPLACE,
           related=["цена"], aliases=["discount"]),
        _e("продавец", "Продавец — сторона оферты WB, размещающая товары на Сайте.", C.WILDBERRIES,
           related=["оферта_wb"], aliases=["seller"]),
        _e("штраф", "Штраф/неустойка WB — только из versioned PolicyEngine / Перечня штрафов актуальной оферты.", C.WILDBERRIES,
           mistakes=["Называть сумму без актуальной редакции."],
           related=["оферта_wb", "удержания"], aliases=["penalties", "штрафы", "неустойка"]),
        _e("поставка", "Поставка — отгрузка товара на склад WB по Плану поставок.", C.WILDBERRIES,
           related=["FBW", "stock"], aliases=["supply", "поставки"]),
        _e("остатки", "Остаток — доступное к продаже количество.", C.MARKETPLACE,
           related=["оборачиваемость", "FBS"], aliases=["stock", "остаток"]),
        _e("реклама_mp", "Реклама на маркетплейсе — кампании продвижения карточки.", C.MARKETPLACE,
           related=["CTR", "CPC", "рекламные_расходы"], aliases=["реклама wb", "продвижение"]),
        _e("заказы", "Заказы — оформленные заказы за период.", C.METRICS,
           related=["CVR", "выкуп"], aliases=["orders", "заказ"]),
        _e("выкуп", "Выкуп — доля/факт оплаты и получения заказа покупателем.", C.MARKETPLACE,
           related=["заказы", "отмены"], aliases=["purchase rate", "процент выкупа"]),
        _e("отмены", "Отмены — отменённые заказы (покупатель/продавец/площадка).", C.MARKETPLACE,
           related=["заказы", "выкуп"], aliases=["cancellations", "cancel"]),
        _e("FBS", "Fulfillment by Seller — товар на складе продавца, передача WB для доставки.", C.MARKETPLACE,
           related=["FBW", "DBS"], aliases=["fbs", "фбс", "маркетплейс модель"]),
        _e("FBW", "Fulfillment by Wildberries (FBO) — товар на складе WB.", C.WILDBERRIES,
           related=["FBS", "поставка"], aliases=["fbw", "fbo", "фбо", "фбв"]),
        _e("DBS", "Delivery by Seller / Витрина — доставка силами продавца.", C.MARKETPLACE,
           related=["FBS"], aliases=["dbs", "витрина"]),
        _e("ratings", "Рейтинг карточки/продавца — агрегированные оценки покупателей.", C.MARKETPLACE,
           related=["reviews"], aliases=["рейтинг", "rating"]),
        _e("reviews", "Отзывы. card feedbacks ≠ processed review intelligence.", C.MARKETPLACE,
           mistakes=["Путать число на карточке с числом обработанных RI."],
           related=["ratings"], aliases=["отзывы"]),
        _e("оферта_wb", "Оферта WB — договор присоединения продавца. Актуальная версия — в кабинете Partners → Оферты.", C.WILDBERRIES,
           related=["штраф", "удержания"], aliases=["оферта", "offer wb"]),
        _e("удержания", "Удержания из выручки: вознаграждение, услуги, неустойки (п. 6.1/6.9 оферты).", C.WILDBERRIES,
           related=["комиссии", "штраф"], aliases=["withholdings"]),
        _e("unit_economics_mp", "Unit economics на маркетплейсе — UnitProfit с учётом комиссии, логистики, хранения, рекламы, возвратов, штрафов (только KNOWN).", C.MARKETPLACE,
           related=["unit_economics", "UnitProfit"], aliases=["unit economics marketplace"]),
    ]

    return e


# Back-compat for seed.py callers
def build_seed_entries() -> list[E]:
    return build_seed_entries_v2()
